-- Run this in Supabase: Dashboard → SQL Editor → New query → paste and Run
--
-- Creates a table to capture onboarding survey responses so we can see:
--   • Where users heard about WriteScholar (marketing channel attribution)
--   • What they're using it for       (use-case / goal signal)
--   • Which features excited them most (product roadmap signal)
--
-- One row per user (unique on user_id, upserted on every onboarding submission).
--
-- ⚠ IMPORTANT — user_id references public.users(id), NOT auth.users(id).
--   This app uses its own JWT-based auth with a public.users table (see
--   backend/src/database/schema.sql), not Supabase Auth. An earlier version
--   of this file pointed at auth.users which caused EVERY insert to fail
--   with a foreign-key violation (the app's user UUIDs only live in
--   public.users). If your existing table still has the bad FK, run the
--   migration block at the bottom of this file to repair it.

CREATE TABLE IF NOT EXISTS onboarding_survey_responses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  referral_source TEXT,
  use_goal TEXT,
  feature_interests TEXT[],
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT onboarding_survey_unique_user UNIQUE (user_id)
);

-- For existing tables, add the new column if it isn't there yet:
ALTER TABLE onboarding_survey_responses
  ADD COLUMN IF NOT EXISTS use_goal TEXT;

CREATE INDEX IF NOT EXISTS idx_onboarding_survey_user      ON onboarding_survey_responses(user_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_survey_source    ON onboarding_survey_responses(referral_source);
CREATE INDEX IF NOT EXISTS idx_onboarding_survey_goal      ON onboarding_survey_responses(use_goal);
CREATE INDEX IF NOT EXISTS idx_onboarding_survey_submitted ON onboarding_survey_responses(submitted_at DESC);

-- ─────────────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
--
-- We enable RLS to satisfy Supabase's security warning, but no policies are
-- created — only the backend (using SUPABASE_SERVICE_ROLE_KEY, which
-- bypasses RLS) ever writes to this table. The previous policies referenced
-- auth.uid() which is meaningless in this app: WriteScholar uses JWT-based
-- auth against public.users, not Supabase Auth. Those policies would have
-- denied direct client access anyway, so omitting them is functionally
-- equivalent and clearer.
-- ─────────────────────────────────────────────────────────────────────

ALTER TABLE onboarding_survey_responses ENABLE ROW LEVEL SECURITY;

-- NOTE: the service_role key bypasses all RLS, so the backend's existing
-- inserts/upserts continue to work without any code changes.

-- ─────────────────────────────────────────────────────────────────────
-- REPAIR MIGRATION (run this if the table was created under the older
-- schema where user_id pointed at auth.users(id) — the FK violation that
-- silently broke every survey insert).
--
-- Safe to run repeatedly; the IF EXISTS / IF NOT EXISTS guards keep it
-- idempotent. After running this once you should be able to confirm fix
-- by submitting a fresh onboarding survey and seeing a row appear in
-- onboarding_survey_responses for that user.
-- ─────────────────────────────────────────────────────────────────────

-- Drop the broken FK if it exists (constraint name auto-generated by Postgres)
ALTER TABLE onboarding_survey_responses
  DROP CONSTRAINT IF EXISTS onboarding_survey_responses_user_id_fkey;

-- Re-add it pointing at the right table
ALTER TABLE onboarding_survey_responses
  ADD CONSTRAINT onboarding_survey_responses_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

-- ─────────────────────────────────────────────────────────────────────
-- USEFUL ANALYTICS QUERIES (copy/paste in Supabase SQL Editor)
-- ─────────────────────────────────────────────────────────────────────

-- 1) Top marketing channels — where new users are coming from:
--    SELECT referral_source, COUNT(*) AS users, ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS pct
--    FROM onboarding_survey_responses
--    WHERE referral_source IS NOT NULL
--    GROUP BY referral_source
--    ORDER BY users DESC;

-- 2) Top use-case goals — what users actually want to accomplish:
--    SELECT use_goal, COUNT(*) AS users, ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS pct
--    FROM onboarding_survey_responses
--    WHERE use_goal IS NOT NULL
--    GROUP BY use_goal
--    ORDER BY users DESC;

-- 3) Most-anticipated features — what to prioritise on the roadmap:
--    SELECT feature, COUNT(*) AS users
--    FROM onboarding_survey_responses, unnest(feature_interests) AS feature
--    GROUP BY feature
--    ORDER BY users DESC;

-- 4) Source × goal crosstab — which channels bring which kind of user:
--    SELECT referral_source, use_goal, COUNT(*) AS users
--    FROM onboarding_survey_responses
--    WHERE referral_source IS NOT NULL AND use_goal IS NOT NULL
--    GROUP BY referral_source, use_goal
--    ORDER BY referral_source, users DESC;

-- 5) Goal × feature crosstab — what features people pick by goal:
--    SELECT use_goal, feature, COUNT(*) AS users
--    FROM onboarding_survey_responses, unnest(feature_interests) AS feature
--    WHERE use_goal IS NOT NULL
--    GROUP BY use_goal, feature
--    ORDER BY use_goal, users DESC;

-- 6) Daily signups by source — see if a TikTok video pushed traffic:
--    SELECT DATE(submitted_at) AS day, referral_source, COUNT(*) AS users
--    FROM onboarding_survey_responses
--    GROUP BY day, referral_source
--    ORDER BY day DESC, users DESC;
