//
//  GeneralTriviaQuestionBank.swift
//  WriteScholar
//
//  Cross-subject trivia: famous quotes, animals, inventions and inventors
//  (historical), astronomy basics, food/cooking, and classic literature.
//  All facts are timeless — no current events, no records, no living
//  records that can be broken.
//

import Foundation

enum GeneralTriviaQuestionBank {

    static let questions: [QuizQuestion] = [
        q(800_000, "Which playwright wrote 'Romeo and Juliet'?",
          ["Christopher Marlowe", "Ben Jonson", "William Shakespeare", "John Webster"], "William Shakespeare",
          "Written in the early 1590s."),
        q(800_001, "Who wrote '1984' and 'Animal Farm'?",
          ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H. G. Wells"], "George Orwell",
          "Pen name of Eric Arthur Blair."),
        q(800_002, "Which novel begins 'Call me Ishmael.'?",
          ["The Old Man and the Sea", "Moby-Dick", "Treasure Island", "The Catcher in the Rye"], "Moby-Dick",
          "Herman Melville, 1851."),
        q(800_003, "Who wrote 'Pride and Prejudice'?",
          ["Jane Austen", "Charlotte Brontë", "George Eliot", "Mary Shelley"], "Jane Austen",
          "Published in 1813."),
        q(800_004, "Who painted 'Starry Night'?",
          ["Claude Monet", "Vincent van Gogh", "Paul Cézanne", "Henri Matisse"], "Vincent van Gogh",
          "Painted in 1889 from his asylum room."),
        q(800_005, "Who wrote 'The Odyssey' and 'The Iliad'?",
          ["Virgil", "Homer", "Ovid", "Sophocles"], "Homer",
          "Ancient Greek epic poet (~8th century BC)."),
        q(800_006, "What's the largest mammal in the world?",
          ["Elephant", "Blue whale", "Giraffe", "Sperm whale"], "Blue whale",
          "Up to ~30 m long and ~180 tonnes."),
        q(800_007, "Which animal is the fastest land animal?",
          ["Lion", "Cheetah", "Pronghorn", "Greyhound"], "Cheetah",
          "Top speeds of about 110 km/h."),
        q(800_008, "Which group of mammals lays eggs?",
          ["Marsupials", "Monotremes", "Placentals", "Rodents"], "Monotremes",
          "Includes the platypus and echidnas."),
        q(800_009, "How many legs does an arachnid have?",
          ["6", "8", "10", "12"], "8",
          "Spiders, scorpions, and ticks are arachnids."),
        q(800_010, "Which planet is famous for its prominent ring system?",
          ["Mars", "Saturn", "Neptune", "Mercury"], "Saturn",
          "All four gas giants have rings; Saturn's are the most striking."),
        q(800_011, "What's the name of our galaxy?",
          ["Andromeda", "Milky Way", "Triangulum", "Magellanic"], "Milky Way",
          "A barred spiral galaxy."),
        q(800_012, "Who invented the telephone (patent 1876)?",
          ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"], "Alexander Graham Bell",
          "Patent granted in 1876."),
        q(800_013, "Who painted 'The Persistence of Memory' (the melting clocks)?",
          ["Pablo Picasso", "Salvador Dalí", "René Magritte", "Joan Miró"], "Salvador Dalí",
          "Painted in 1931."),
        q(800_014, "What's the hardest natural substance on Earth?",
          ["Quartz", "Steel", "Diamond", "Granite"], "Diamond",
          "10 on the Mohs scale of hardness."),
        q(800_015, "What's the main ingredient in guacamole?",
          ["Tomato", "Avocado", "Cucumber", "Pepper"], "Avocado",
          "From the Aztec word 'āhuacamolli'."),
        q(800_016, "Which gas is necessary for combustion?",
          ["Hydrogen", "Carbon dioxide", "Oxygen", "Nitrogen"], "Oxygen",
          "Combustion is rapid oxidation."),
        q(800_017, "How many sides does a hexagon have?",
          ["5", "6", "7", "8"], "6",
          "From Greek 'hex' (six)."),
        q(800_018, "How many sides does an octagon have?",
          ["6", "7", "8", "10"], "8",
          "From Greek 'oktō' (eight)."),
        q(800_019, "How many degrees are in a circle?",
          ["180", "270", "360", "400"], "360",
          "Inherited from Babylonian base-60 mathematics."),
        q(800_020, "How many sides does a dodecagon have?",
          ["10", "11", "12", "14"], "12",
          "Greek 'dodeka' = twelve."),
        q(800_021, "What does the 'www' in a website URL stand for?",
          ["World Wide Web", "Word Wide Web", "Web World Wide", "World Web Width"], "World Wide Web",
          "Coined by Tim Berners-Lee in 1989."),
        q(800_022, "Which English king signed the Magna Carta?",
          ["Richard I", "John", "Henry III", "Edward I"], "John",
          "Signed in 1215 at Runnymede."),
        q(800_023, "Which country gifted the Statue of Liberty to the US?",
          ["United Kingdom", "France", "Spain", "Italy"], "France",
          "Dedicated in 1886."),
        q(800_024, "Which planet is known as the 'Morning Star' or 'Evening Star'?",
          ["Mars", "Jupiter", "Venus", "Mercury"], "Venus",
          "Brightest planet visible from Earth."),
        q(800_025, "Who wrote 'A Christmas Carol'?",
          ["Charles Dickens", "Mark Twain", "Lewis Carroll", "Oscar Wilde"], "Charles Dickens",
          "Published in 1843."),
        q(800_026, "What is the world's longest-running animated series? (Started 1969)",
          ["The Simpsons", "Sazae-san", "South Park", "Tom and Jerry"], "Sazae-san",
          "Japanese anime running since 1969."),
        q(800_027, "Who developed the first effective polio vaccine?",
          ["Louis Pasteur", "Edward Jenner", "Jonas Salk", "Alexander Fleming"], "Jonas Salk",
          "Announced in 1955."),
        q(800_028, "What's the boiling point of water in Fahrenheit?",
          ["180°F", "200°F", "212°F", "240°F"], "212°F",
          "100°C = 212°F at sea level."),
        q(800_029, "How many colours are in a rainbow?",
          ["5", "6", "7", "8"], "7",
          "Red, Orange, Yellow, Green, Blue, Indigo, Violet — ROYGBIV."),
        q(800_030, "What is the chemical symbol for tin?",
          ["Ti", "Tn", "Sn", "T"], "Sn",
          "From the Latin 'stannum'."),
        q(800_031, "Who wrote 'Hamlet'?",
          ["Shakespeare", "Marlowe", "Jonson", "Webster"], "Shakespeare",
          "Written ~1600–1601."),
        q(800_032, "Which animal is sometimes called the 'King of the Jungle'?",
          ["Tiger", "Lion", "Elephant", "Gorilla"], "Lion",
          "Despite mostly living on savannahs, not jungles."),
        q(800_033, "What's the world's smallest bird?",
          ["Hummingbird", "Bee Hummingbird", "Sparrow", "Wren"], "Bee Hummingbird",
          "Found only in Cuba; about 5–6 cm long."),
        q(800_034, "Which inventor patented the light bulb in 1879?",
          ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "Michael Faraday"], "Thomas Edison",
          "Edison developed the first commercially practical bulb."),
        q(800_035, "Who wrote 'The Adventures of Sherlock Holmes'?",
          ["Agatha Christie", "Arthur Conan Doyle", "Edgar Allan Poe", "G. K. Chesterton"], "Arthur Conan Doyle",
          "Holmes first appeared in 1887's 'A Study in Scarlet'.")
    ]

    static let flashcards: [Flashcard] = [
        Flashcard(front: "Largest mammal",            back: "The blue whale."),
        Flashcard(front: "Fastest land animal",       back: "The cheetah."),
        Flashcard(front: "Hardest natural substance", back: "Diamond."),
        Flashcard(front: "Sides of a hexagon",        back: "Six."),
        Flashcard(front: "Sides of an octagon",       back: "Eight."),
        Flashcard(front: "Author of Romeo and Juliet", back: "William Shakespeare."),
        Flashcard(front: "Author of 1984",            back: "George Orwell.")
    ]

    private static func q(_ id: Int, _ q: String, _ opts: [String], _ correct: String, _ why: String) -> QuizQuestion {
        QuizQuestion(id: id, type: .multipleChoice, question: q, options: opts, correctAnswer: correct, explanation: why)
    }
}
