//
//  GeographyQuestionBank.swift
//  WriteScholar
//
//  Capitals, continents, oceans, mountains and rivers — picked to be
//  geographically stable. We avoid populations and disputed borders;
//  capitals can change but the ones included here have been settled
//  for many decades or centuries.
//

import Foundation

enum GeographyQuestionBank {

    static let questions: [QuizQuestion] = [
        q(400_000, "What is the capital of France?",
          ["Lyon", "Paris", "Marseille", "Bordeaux"], "Paris",
          "Capital of France since 987 AD."),
        q(400_001, "What is the capital of Japan?",
          ["Osaka", "Kyoto", "Tokyo", "Nagoya"], "Tokyo",
          "Capital since 1868."),
        q(400_002, "What is the capital of Australia?",
          ["Sydney", "Melbourne", "Canberra", "Perth"], "Canberra",
          "Designated capital in 1908 as a compromise between Sydney and Melbourne."),
        q(400_003, "What is the capital of Canada?",
          ["Toronto", "Ottawa", "Vancouver", "Montreal"], "Ottawa",
          "Chosen as capital by Queen Victoria in 1857."),
        q(400_004, "What is the capital of Brazil?",
          ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], "Brasília",
          "Inaugurated as capital in 1960."),
        q(400_005, "What is the capital of Egypt?",
          ["Alexandria", "Cairo", "Giza", "Luxor"], "Cairo",
          "Founded in 969 AD."),
        q(400_006, "What is the capital of Russia?",
          ["St Petersburg", "Moscow", "Kazan", "Novosibirsk"], "Moscow",
          "Capital of Russia for most of its history (and again since 1918)."),
        q(400_007, "What is the capital of Germany?",
          ["Munich", "Hamburg", "Frankfurt", "Berlin"], "Berlin",
          "Reunited capital since 1990."),
        q(400_008, "What is the capital of Spain?",
          ["Barcelona", "Madrid", "Seville", "Valencia"], "Madrid",
          "Capital since the 16th century."),
        q(400_009, "What is the capital of Italy?",
          ["Milan", "Naples", "Florence", "Rome"], "Rome",
          "Capital since Italian unification in 1871."),
        q(400_010, "What is the capital of India?",
          ["Mumbai", "Kolkata", "New Delhi", "Bangalore"], "New Delhi",
          "Inaugurated as capital in 1931."),
        q(400_011, "What is the capital of South Korea?",
          ["Busan", "Seoul", "Incheon", "Daegu"], "Seoul",
          "Capital of Korea since 1394."),
        q(400_012, "What is the capital of Argentina?",
          ["Córdoba", "Rosario", "Mendoza", "Buenos Aires"], "Buenos Aires",
          "Federalised as capital in 1880."),
        q(400_013, "What is the capital of Greece?",
          ["Thessaloniki", "Athens", "Patras", "Heraklion"], "Athens",
          "Capital since 1834; one of the world's oldest cities."),
        q(400_014, "How many continents are there?",
          ["5", "6", "7", "8"], "7",
          "Africa, Antarctica, Asia, Australia/Oceania, Europe, North America, South America."),
        q(400_015, "Which continent is Egypt mostly in?",
          ["Asia", "Europe", "Africa", "Middle East"], "Africa",
          "The Sinai Peninsula is in Asia, but Egypt is mostly African."),
        q(400_016, "What is the largest ocean on Earth?",
          ["Atlantic", "Indian", "Arctic", "Pacific"], "Pacific",
          "Covers about a third of the Earth's surface."),
        q(400_017, "What is the longest river in the world?",
          ["Amazon", "Nile", "Yangtze", "Mississippi"], "Nile",
          "About 6,650 km long. (Some studies favour the Amazon — Nile is the textbook answer.)"),
        q(400_018, "What is the highest mountain on Earth?",
          ["K2", "Kangchenjunga", "Makalu", "Mount Everest"], "Mount Everest",
          "8,848.86 m above sea level."),
        q(400_019, "Which desert is the largest hot desert in the world?",
          ["Gobi", "Sahara", "Kalahari", "Atacama"], "Sahara",
          "About 9.2 million km²."),
        q(400_020, "Which mountain range separates Europe from Asia?",
          ["Alps", "Pyrenees", "Urals", "Caucasus"], "Urals",
          "Runs north–south through western Russia."),
        q(400_021, "Which sea lies between Europe and Africa?",
          ["Black Sea", "Caspian Sea", "Mediterranean Sea", "North Sea"], "Mediterranean Sea",
          "Connected to the Atlantic by the Strait of Gibraltar."),
        q(400_022, "On which continent is the Amazon rainforest mostly located?",
          ["Africa", "Asia", "South America", "Oceania"], "South America",
          "Mostly in Brazil, with parts in Peru, Colombia, and others."),
        q(400_023, "Which river flows through London?",
          ["Severn", "Thames", "Trent", "Mersey"], "Thames",
          "Flows about 346 km through southern England."),
        q(400_024, "Which strait separates England from France?",
          ["Strait of Dover", "Strait of Gibraltar", "Strait of Hormuz", "Strait of Magellan"], "Strait of Dover",
          "About 33 km at its narrowest."),
        q(400_025, "Which country has the most time zones?",
          ["USA", "Russia", "China", "France"], "France",
          "Including overseas territories, France spans 12 time zones."),
        q(400_026, "Which country is shaped like a boot?",
          ["Spain", "Italy", "Greece", "Portugal"], "Italy",
          "Italian Peninsula juts into the Mediterranean."),
        q(400_027, "What is the smallest country in the world?",
          ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], "Vatican City",
          "About 0.49 km²."),
        q(400_028, "Which country is both in Europe and Asia, with Istanbul as its largest city?",
          ["Greece", "Turkey", "Iran", "Russia"], "Turkey",
          "Istanbul straddles the Bosphorus."),
        q(400_029, "Which Scandinavian capital is built on 14 islands?",
          ["Oslo", "Copenhagen", "Stockholm", "Helsinki"], "Stockholm",
          "Connected by 57 bridges."),
        q(400_030, "On which river does Paris sit?",
          ["Loire", "Rhône", "Seine", "Garonne"], "Seine",
          "Flows through northern France into the English Channel."),
        q(400_031, "Which African country has the most pyramids?",
          ["Egypt", "Sudan", "Libya", "Morocco"], "Sudan",
          "Sudan has more than 200 known pyramids."),
        q(400_032, "Which is the largest country by area?",
          ["Canada", "China", "USA", "Russia"], "Russia",
          "About 17.1 million km²."),
        q(400_033, "Which country uses the yen as its currency?",
          ["China", "Japan", "South Korea", "Thailand"], "Japan",
          "Symbol ¥."),
        q(400_034, "Which mountain range runs along the western edge of South America?",
          ["Rockies", "Atlas", "Andes", "Himalayas"], "Andes",
          "About 7,000 km long — the world's longest mountain range."),
        q(400_035, "What is the capital of Portugal?",
          ["Porto", "Lisbon", "Faro", "Coimbra"], "Lisbon",
          "Capital since the 13th century."),
        q(400_036, "Which country is divided by the equator and contains the Galápagos Islands?",
          ["Peru", "Colombia", "Ecuador", "Venezuela"], "Ecuador",
          "Named for the equator that crosses it."),
        q(400_037, "Which is the smallest continent by area?",
          ["Europe", "Antarctica", "Australia/Oceania", "South America"], "Australia/Oceania",
          "About 8.6 million km²."),
        q(400_038, "Which European city is known as the City of Canals?",
          ["Amsterdam", "Bruges", "Stockholm", "Venice"], "Venice",
          "Built across 118 islands in a lagoon.")
    ]

    static let flashcards: [Flashcard] = [
        Flashcard(front: "Capital of France",      back: "Paris."),
        Flashcard(front: "Capital of Japan",       back: "Tokyo."),
        Flashcard(front: "Capital of Australia",   back: "Canberra."),
        Flashcard(front: "Capital of Canada",      back: "Ottawa."),
        Flashcard(front: "Capital of Brazil",      back: "Brasília (since 1960)."),
        Flashcard(front: "Largest ocean",          back: "Pacific Ocean."),
        Flashcard(front: "Longest river",          back: "The Nile (~6,650 km)."),
        Flashcard(front: "Highest mountain",       back: "Mount Everest (~8,849 m)."),
        Flashcard(front: "Largest hot desert",     back: "Sahara Desert."),
        Flashcard(front: "Smallest country",       back: "Vatican City (~0.49 km²).")
    ]

    private static func q(_ id: Int, _ q: String, _ opts: [String], _ correct: String, _ why: String) -> QuizQuestion {
        QuizQuestion(id: id, type: .multipleChoice, question: q, options: opts, correctAnswer: correct, explanation: why)
    }
}
