//
//  HistoryQuestionBank.swift
//  WriteScholar
//
//  Curated history questions, all anchored to events more than 50 years
//  in the past. No current officeholders, no recent records — just
//  textbook history that won't shift over time.
//

import Foundation

enum HistoryQuestionBank {

    static let questions: [QuizQuestion] = [
        q(300_000, "In which year did World War II end?",
          ["1942", "1944", "1945", "1947"], "1945",
          "Germany surrendered in May 1945; Japan in September 1945."),
        q(300_001, "In which year did World War I begin?",
          ["1910", "1912", "1914", "1916"], "1914",
          "Triggered by the assassination of Archduke Franz Ferdinand."),
        q(300_002, "Who was the first President of the United States?",
          ["Thomas Jefferson", "John Adams", "George Washington", "Benjamin Franklin"], "George Washington",
          "Inaugurated in 1789."),
        q(300_003, "In which year did the French Revolution begin?",
          ["1769", "1789", "1799", "1812"], "1789",
          "Marked by the storming of the Bastille on July 14, 1789."),
        q(300_004, "Who painted the Mona Lisa?",
          ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], "Leonardo da Vinci",
          "Painted between 1503 and 1519."),
        q(300_005, "Which empire was ruled by Julius Caesar?",
          ["Greek", "Roman", "Persian", "Egyptian"], "Roman",
          "He was a Roman general and statesman, assassinated 44 BC."),
        q(300_006, "Which civilization built Machu Picchu?",
          ["Aztec", "Maya", "Inca", "Olmec"], "Inca",
          "Built in the 15th century in the Peruvian Andes."),
        q(300_007, "Who wrote the Communist Manifesto with Friedrich Engels?",
          ["Vladimir Lenin", "Joseph Stalin", "Karl Marx", "Leon Trotsky"], "Karl Marx",
          "Published in 1848."),
        q(300_008, "Which document begins 'We the People'?",
          ["Declaration of Independence", "Magna Carta", "US Constitution", "Bill of Rights"], "US Constitution",
          "Ratified in 1788."),
        q(300_009, "Who was the British Prime Minister during most of WWII?",
          ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Harold Wilson"], "Winston Churchill",
          "PM 1940–1945 (and again 1951–1955)."),
        q(300_010, "Which year did the Berlin Wall fall?",
          ["1987", "1989", "1991", "1993"], "1989",
          "Marked the symbolic end of the Cold War."),
        q(300_011, "Which queen reigned during much of the Spanish Armada conflict?",
          ["Mary I", "Elizabeth I", "Anne", "Victoria"], "Elizabeth I",
          "The Armada was defeated in 1588."),
        q(300_012, "Who led the Soviet Union during WWII?",
          ["Lenin", "Trotsky", "Stalin", "Khrushchev"], "Stalin",
          "Joseph Stalin led from 1924 until his death in 1953."),
        q(300_013, "Which civilization built the pyramids at Giza?",
          ["Mesopotamian", "Roman", "Greek", "Egyptian"], "Egyptian",
          "Constructed during Egypt's Old Kingdom (~2580–2560 BC)."),
        q(300_014, "Who was the first emperor of China?",
          ["Qin Shi Huang", "Sun Yat-sen", "Kublai Khan", "Han Wudi"], "Qin Shi Huang",
          "Unified China in 221 BC."),
        q(300_015, "In which year was the Magna Carta signed?",
          ["1066", "1215", "1314", "1492"], "1215",
          "Signed by King John of England at Runnymede."),
        q(300_016, "Which event in 1066 reshaped England?",
          ["Norman Conquest", "Wars of the Roses", "Battle of Bosworth", "Glorious Revolution"], "Norman Conquest",
          "William the Conqueror defeated Harold at Hastings."),
        q(300_017, "Who wrote 'The Prince', a 16th-century treatise on power?",
          ["Galileo", "Niccolò Machiavelli", "Petrarch", "Dante"], "Niccolò Machiavelli",
          "Written in 1513."),
        q(300_018, "Which civilization is credited with inventing democracy?",
          ["Roman", "Greek", "Persian", "Egyptian"], "Greek",
          "Athenian democracy emerged in the 5th century BC."),
        q(300_019, "Who discovered the Americas for the Spanish Crown in 1492?",
          ["Vasco da Gama", "Christopher Columbus", "Ferdinand Magellan", "Hernán Cortés"], "Christopher Columbus",
          "Made landfall in the Bahamas in October 1492."),
        q(300_020, "Which ancient wonder stood in Alexandria?",
          ["Hanging Gardens", "Colossus", "Lighthouse", "Mausoleum"], "Lighthouse",
          "The Pharos of Alexandria, built ~280 BC."),
        q(300_021, "Which treaty ended World War I?",
          ["Treaty of Paris", "Treaty of Versailles", "Treaty of Trianon", "Treaty of Westphalia"], "Treaty of Versailles",
          "Signed in 1919."),
        q(300_022, "Which leader was assassinated in 1865?",
          ["John F. Kennedy", "Abraham Lincoln", "William McKinley", "James Garfield"], "Abraham Lincoln",
          "Shot at Ford's Theatre by John Wilkes Booth."),
        q(300_023, "Who was the queen of England known as the 'Virgin Queen'?",
          ["Mary I", "Elizabeth I", "Anne", "Victoria"], "Elizabeth I",
          "Reigned 1558–1603 and never married."),
        q(300_024, "Which empire fell in 476 AD?",
          ["Byzantine Empire", "Western Roman Empire", "Holy Roman Empire", "Persian Empire"], "Western Roman Empire",
          "When Romulus Augustulus was deposed."),
        q(300_025, "What is the name of the 1215 charter limiting royal power in England?",
          ["Bill of Rights", "Magna Carta", "Domesday Book", "Habeas Corpus"], "Magna Carta",
          "Forced on King John by his barons."),
        q(300_026, "Who painted the Sistine Chapel ceiling?",
          ["Leonardo da Vinci", "Raphael", "Michelangelo", "Botticelli"], "Michelangelo",
          "Completed in 1512."),
        q(300_027, "In which century did the Industrial Revolution begin in Britain?",
          ["17th", "18th", "19th", "20th"], "18th",
          "Roughly 1760 onward."),
        q(300_028, "Which 1776 document declared American independence?",
          ["Articles of Confederation", "Declaration of Independence", "Bill of Rights", "Constitution"], "Declaration of Independence",
          "Adopted on July 4, 1776."),
        q(300_029, "What was the network of trade routes between China and Europe called?",
          ["Spice Route", "Silk Road", "Tea Trail", "Amber Road"], "Silk Road",
          "Active from roughly 130 BC to 1453 AD."),
        q(300_030, "Who led the Mongol Empire's expansion in the early 13th century?",
          ["Kublai Khan", "Genghis Khan", "Tamerlane", "Attila"], "Genghis Khan",
          "Founded the Mongol Empire in 1206."),
        q(300_031, "Which dynasty ruled China for almost 300 years until 1644?",
          ["Tang", "Song", "Ming", "Qing"], "Ming",
          "1368–1644, founded by Zhu Yuanzhang."),
        q(300_032, "Who was the leader of Nazi Germany during WWII?",
          ["Heinrich Himmler", "Adolf Hitler", "Hermann Göring", "Joseph Goebbels"], "Adolf Hitler",
          "Chancellor 1933–1945."),
        q(300_033, "Which battle in 1815 ended the Napoleonic Wars?",
          ["Battle of Trafalgar", "Battle of Austerlitz", "Battle of Waterloo", "Battle of Borodino"], "Battle of Waterloo",
          "Wellington and Blücher defeated Napoleon."),
        q(300_034, "Who composed the symphonies known as 'Eroica' and 'Pastoral'?",
          ["Mozart", "Beethoven", "Bach", "Brahms"], "Beethoven",
          "His 3rd and 6th symphonies."),
        q(300_035, "Which religion did Constantine the Great legalize in 313 AD?",
          ["Islam", "Christianity", "Judaism", "Buddhism"], "Christianity",
          "Through the Edict of Milan."),
        q(300_036, "Who wrote 'The Wealth of Nations' (1776)?",
          ["Karl Marx", "John Maynard Keynes", "Adam Smith", "David Ricardo"], "Adam Smith",
          "Foundational work of classical economics."),
        q(300_037, "Which 14th-century pandemic killed an estimated third of Europe?",
          ["Spanish Flu", "Smallpox", "Black Death", "Cholera"], "Black Death",
          "Peaked in Europe between 1347 and 1351."),
        q(300_038, "Who was the long-reigning British queen of the 19th century?",
          ["Victoria", "Elizabeth I", "Anne", "Mary II"], "Victoria",
          "Reigned 1837–1901 — over 63 years."),
        q(300_039, "Which leader led India's independence movement through non-violence?",
          ["Jawaharlal Nehru", "Mahatma Gandhi", "Subhas Chandra Bose", "B. R. Ambedkar"], "Mahatma Gandhi",
          "India became independent in 1947.")
    ]

    static let flashcards: [Flashcard] = [
        Flashcard(front: "Magna Carta",            back: "1215 charter limiting English royal power, signed by King John."),
        Flashcard(front: "Treaty of Versailles",   back: "1919 peace treaty that ended WWI between Germany and the Allies."),
        Flashcard(front: "Renaissance",            back: "Cultural rebirth in Europe roughly 14th–17th centuries, centred in Italy."),
        Flashcard(front: "Industrial Revolution",  back: "Late-18th-century shift from manual to machine-based production, beginning in Britain."),
        Flashcard(front: "Silk Road",              back: "Network of trade routes connecting China with the Mediterranean (~130 BC–1453 AD)."),
        Flashcard(front: "Black Death",            back: "Mid-14th-century plague pandemic that killed about a third of Europe."),
        Flashcard(front: "Norman Conquest",        back: "1066 conquest of England by William, Duke of Normandy."),
        Flashcard(front: "Reformation",            back: "16th-century movement, sparked by Martin Luther in 1517, that split Western Christianity."),
        Flashcard(front: "Storming of the Bastille", back: "July 14, 1789 — symbolic start of the French Revolution."),
        Flashcard(front: "Pax Romana",             back: "About 200 years of relative peace across the Roman Empire (27 BC – AD 180).")
    ]

    private static func q(_ id: Int, _ q: String, _ opts: [String], _ correct: String, _ why: String) -> QuizQuestion {
        QuizQuestion(id: id, type: .multipleChoice, question: q, options: opts, correctAnswer: correct, explanation: why)
    }
}
