//
//  ScienceQuestionBank.swift
//  WriteScholar
//
//  Hand-curated, timeless science questions: periodic table basics,
//  cell biology, physics laws, anatomy. None of these answers change
//  with the news cycle — they're textbook fundamentals.
//

import Foundation

enum ScienceQuestionBank {

    static let questions: [QuizQuestion] = [
        q(200_000, "What is the chemical symbol for gold?",
          ["Au", "Ag", "Gd", "Go"], "Au",
          "From the Latin 'aurum'."),
        q(200_001, "What is the chemical symbol for sodium?",
          ["So", "Na", "Sd", "Ne"], "Na",
          "From the Latin 'natrium'."),
        q(200_002, "What is the chemical symbol for iron?",
          ["Ir", "In", "Fe", "Fr"], "Fe",
          "From the Latin 'ferrum'."),
        q(200_003, "What is the chemical symbol for potassium?",
          ["P", "Pt", "Po", "K"], "K",
          "From the Latin 'kalium'."),
        q(200_004, "What is the chemical symbol for silver?",
          ["Si", "Sl", "Ag", "Sv"], "Ag",
          "From the Latin 'argentum'."),
        q(200_005, "What is the atomic number of hydrogen?",
          ["0", "1", "2", "3"], "1",
          "Hydrogen is the lightest and simplest element."),
        q(200_006, "What is the atomic number of carbon?",
          ["4", "6", "8", "12"], "6",
          "Carbon has 6 protons in its nucleus."),
        q(200_007, "What gas do plants absorb during photosynthesis?",
          ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], "Carbon dioxide",
          "CO₂ is converted to glucose using light energy."),
        q(200_008, "What is the powerhouse of the cell?",
          ["Ribosome", "Nucleus", "Mitochondrion", "Golgi apparatus"], "Mitochondrion",
          "Mitochondria generate most of the cell's ATP."),
        q(200_009, "Which organelle contains the cell's DNA?",
          ["Nucleus", "Vacuole", "Lysosome", "Cytoplasm"], "Nucleus",
          "The nucleus stores the chromosomes."),
        q(200_010, "How many bones are in the adult human body?",
          ["186", "206", "226", "246"], "206",
          "Babies are born with about 270; many fuse over time."),
        q(200_011, "How many chambers does the human heart have?",
          ["2", "3", "4", "5"], "4",
          "Two atria and two ventricles."),
        q(200_012, "What's the largest organ in the human body?",
          ["Liver", "Brain", "Skin", "Lungs"], "Skin",
          "Skin covers about 1.5–2 m² in adults."),
        q(200_013, "Which blood cells fight infection?",
          ["Red blood cells", "White blood cells", "Platelets", "Plasma"], "White blood cells",
          "Leukocytes are the immune system's frontline."),
        q(200_014, "What does DNA stand for?",
          ["Deoxyribonucleic acid", "Dinitrogen acetate", "Deoxynitric acid", "Diribonucleic acid"], "Deoxyribonucleic acid",
          "The double-helix carrier of genetic information."),
        q(200_015, "How many planets are in our solar system?",
          ["7", "8", "9", "10"], "8",
          "Pluto was reclassified as a dwarf planet in 2006."),
        q(200_016, "Which planet is closest to the Sun?",
          ["Venus", "Mercury", "Earth", "Mars"], "Mercury",
          "Mercury orbits at about 58 million km from the Sun."),
        q(200_017, "Which planet is known as the Red Planet?",
          ["Mars", "Jupiter", "Venus", "Saturn"], "Mars",
          "Iron oxide on its surface gives it the red colour."),
        q(200_018, "What is the speed of light in a vacuum (approx)?",
          ["300,000 km/s", "150,000 km/s", "1,000 km/s", "3,000,000 km/s"], "300,000 km/s",
          "Roughly 299,792 km/s — denoted c."),
        q(200_019, "Who proposed the three laws of motion?",
          ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"], "Isaac Newton",
          "Published in his Principia Mathematica (1687)."),
        q(200_020, "Newton's first law is also known as the law of…",
          ["Inertia", "Acceleration", "Conservation", "Gravity"], "Inertia",
          "Objects stay at rest or in uniform motion unless acted on."),
        q(200_021, "What's the formula for water?",
          ["H2O", "HO2", "H3O", "OH2"], "H2O",
          "Two hydrogen atoms bonded to one oxygen."),
        q(200_022, "What's the pH of pure water at 25°C?",
          ["5", "6", "7", "8"], "7",
          "Neutral on the pH scale."),
        q(200_023, "Which scientist proposed the theory of evolution by natural selection?",
          ["Gregor Mendel", "Charles Darwin", "Louis Pasteur", "Isaac Newton"], "Charles Darwin",
          "Published in 'On the Origin of Species' (1859)."),
        q(200_024, "What is the boiling point of water at sea level (°C)?",
          ["90", "95", "100", "110"], "100",
          "1 atm of pressure, 100 °C."),
        q(200_025, "What is the freezing point of water (°C)?",
          ["−10", "0", "5", "10"], "0",
          "Defined as the lower fixed point on the Celsius scale."),
        q(200_026, "What part of the cell controls what enters and leaves?",
          ["Cell wall", "Nucleus", "Cell membrane", "Cytoplasm"], "Cell membrane",
          "A semi-permeable phospholipid bilayer."),
        q(200_027, "Which gas makes up about 78% of Earth's atmosphere?",
          ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"], "Nitrogen",
          "Oxygen is about 21%, the rest mostly argon and CO₂."),
        q(200_028, "What's the unit of electrical resistance?",
          ["Volt", "Ampere", "Watt", "Ohm"], "Ohm",
          "Symbol Ω, named after Georg Ohm."),
        q(200_029, "How many pairs of chromosomes do humans have?",
          ["21", "22", "23", "24"], "23",
          "46 chromosomes total, paired."),
        q(200_030, "Which vitamin is produced when skin is exposed to sunlight?",
          ["A", "B12", "C", "D"], "D",
          "UVB triggers vitamin D synthesis in the skin."),
        q(200_031, "Which has more energy: a photon of red light or blue light?",
          ["Red", "Blue", "Same", "Depends"], "Blue",
          "Higher frequency = higher energy (E = hf)."),
        q(200_032, "What's the smallest unit of an element that retains its properties?",
          ["Atom", "Molecule", "Cell", "Quark"], "Atom",
          "Smaller particles (protons, electrons) are not the element itself."),
        q(200_033, "What's the process plants use to make food?",
          ["Respiration", "Fermentation", "Photosynthesis", "Transpiration"], "Photosynthesis",
          "Light + CO₂ + H₂O → glucose + O₂."),
        q(200_034, "Which blood vessel carries oxygen-rich blood from the heart?",
          ["Vein", "Capillary", "Artery", "Aorta"], "Artery",
          "The aorta is the largest artery."),
        q(200_035, "What's the main gas humans exhale?",
          ["Oxygen", "Carbon dioxide", "Nitrogen", "Helium"], "Carbon dioxide",
          "We breathe out CO₂ from cellular respiration."),
        q(200_036, "Sound travels fastest through which medium?",
          ["Vacuum", "Air", "Water", "Steel"], "Steel",
          "Sound travels faster in denser, more elastic media."),
        q(200_037, "Which force keeps planets in orbit around the Sun?",
          ["Magnetism", "Friction", "Gravity", "Electromagnetism"], "Gravity",
          "Gravity is the long-range attractive force between masses."),
        q(200_038, "Who developed the theory of general relativity?",
          ["Niels Bohr", "Albert Einstein", "Marie Curie", "Stephen Hawking"], "Albert Einstein",
          "Published in 1915."),
        q(200_039, "What's the chemical formula for table salt?",
          ["NaCl", "KCl", "CaCl2", "NaHCO3"], "NaCl",
          "Sodium chloride."),
        q(200_040, "What's the largest planet in our solar system?",
          ["Saturn", "Neptune", "Jupiter", "Uranus"], "Jupiter",
          "About 318× the mass of Earth."),
        q(200_041, "What's the densest naturally occurring element?",
          ["Lead", "Gold", "Osmium", "Tungsten"], "Osmium",
          "About 22.59 g/cm³."),
        q(200_042, "Which scientist is credited with discovering penicillin?",
          ["Marie Curie", "Alexander Fleming", "Louis Pasteur", "Edward Jenner"], "Alexander Fleming",
          "Discovered in 1928 from Penicillium mould."),
        q(200_043, "What's the SI base unit of mass?",
          ["Gram", "Kilogram", "Pound", "Ounce"], "Kilogram",
          "Defined via Planck's constant since 2019."),
        q(200_044, "Which subatomic particle has a positive charge?",
          ["Electron", "Proton", "Neutron", "Photon"], "Proton",
          "Located in the nucleus alongside neutrons.")
    ]

    static let flashcards: [Flashcard] = [
        Flashcard(front: "Newton's 1st law",       back: "An object stays at rest, or moves uniformly, unless acted on by a net external force."),
        Flashcard(front: "Newton's 2nd law",       back: "F = m × a (force equals mass times acceleration)."),
        Flashcard(front: "Newton's 3rd law",       back: "For every action there is an equal and opposite reaction."),
        Flashcard(front: "Photosynthesis",         back: "6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂."),
        Flashcard(front: "Cellular respiration",   back: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP."),
        Flashcard(front: "Avogadro's number",      back: "≈ 6.022 × 10²³ — particles in one mole."),
        Flashcard(front: "Speed of light (c)",     back: "≈ 299,792,458 m/s in a vacuum."),
        Flashcard(front: "Mitosis",                back: "Cell division producing two identical daughter cells."),
        Flashcard(front: "Meiosis",                back: "Cell division producing four genetically distinct gametes."),
        Flashcard(front: "DNA",                    back: "Deoxyribonucleic acid — the double-helix carrier of genetic instructions."),
        Flashcard(front: "RNA",                    back: "Ribonucleic acid — single-stranded; carries genetic info from DNA to ribosomes."),
        Flashcard(front: "pH 7",                   back: "Neutral pH — pure water."),
        Flashcard(front: "Ohm's law",              back: "V = I × R."),
        Flashcard(front: "Conservation of energy", back: "Energy cannot be created or destroyed — only transformed.")
    ]

    private static func q(_ id: Int, _ q: String, _ opts: [String], _ correct: String, _ why: String) -> QuizQuestion {
        QuizQuestion(id: id, type: .multipleChoice, question: q, options: opts, correctAnswer: correct, explanation: why)
    }
}
