//
//  VocabularyQuestionBank.swift
//  WriteScholar
//
//  Word definitions, literary devices, and roots/etymology — all
//  timeless. Tests recall plus light reasoning.
//

import Foundation

enum VocabularyQuestionBank {

    static let questions: [QuizQuestion] = [
        q(500_000, "What does 'ephemeral' mean?",
          ["Lasting forever", "Lasting a very short time", "Without form", "Above all others"], "Lasting a very short time",
          "From Greek 'ephēmeros' — lasting a day."),
        q(500_001, "What does 'ubiquitous' mean?",
          ["Strange or rare", "Present everywhere", "Difficult to define", "Slow-moving"], "Present everywhere",
          "From Latin 'ubique' — everywhere."),
        q(500_002, "What does 'gregarious' mean?",
          ["Very shy", "Sociable", "Bad-tempered", "Disorganised"], "Sociable",
          "From Latin 'grex, gregis' — flock."),
        q(500_003, "Which figure of speech is 'as quiet as a mouse'?",
          ["Metaphor", "Simile", "Hyperbole", "Onomatopoeia"], "Simile",
          "Similes use 'like' or 'as' to compare."),
        q(500_004, "Which figure of speech is 'her smile is sunshine'?",
          ["Metaphor", "Simile", "Personification", "Alliteration"], "Metaphor",
          "Direct equivalence without 'like' or 'as'."),
        q(500_005, "What is alliteration?",
          ["Repeated vowel sounds", "Repeated initial consonant sounds", "Words that mimic sounds", "Comparison using 'like'"], "Repeated initial consonant sounds",
          "E.g. 'Peter Piper picked a peck of pickled peppers.'"),
        q(500_006, "What is onomatopoeia?",
          ["A figure of speech using exaggeration", "A word that imitates a sound", "A type of metaphor", "A rhyming pattern"], "A word that imitates a sound",
          "E.g. 'buzz', 'crash', 'whisper'."),
        q(500_007, "What does 'cacophony' mean?",
          ["Pleasant melody", "Harsh, jarring sound", "A musical scale", "An echo"], "Harsh, jarring sound",
          "From Greek 'kakos' (bad) + 'phōnē' (sound)."),
        q(500_008, "What is hyperbole?",
          ["Understatement for effect", "Deliberate exaggeration", "Comparison using 'like'", "An unanswered question"], "Deliberate exaggeration",
          "E.g. 'I've told you a million times!'"),
        q(500_009, "What does 'verbose' mean?",
          ["Using few words", "Using too many words", "Speaking softly", "Speaking loudly"], "Using too many words",
          "From Latin 'verbosus' — wordy."),
        q(500_010, "What does the prefix 'pre-' mean?",
          ["After", "Against", "Before", "Beneath"], "Before",
          "Latin 'prae' — before, in front of."),
        q(500_011, "What does the prefix 'post-' mean?",
          ["Before", "After", "Around", "Inside"], "After",
          "Latin 'post' — after, behind."),
        q(500_012, "What does the suffix '-phobia' mean?",
          ["Love of", "Fear of", "Study of", "Power of"], "Fear of",
          "Greek 'phobos' — fear."),
        q(500_013, "What does the suffix '-ology' mean?",
          ["Fear of", "Study of", "Love of", "Hatred of"], "Study of",
          "Greek 'logia' — study."),
        q(500_014, "What does 'malevolent' mean?",
          ["Wishing good", "Wishing ill", "Indifferent", "Confused"], "Wishing ill",
          "Latin 'mal' (bad) + 'volens' (wishing)."),
        q(500_015, "What does 'benevolent' mean?",
          ["Wishing good", "Wishing ill", "Powerful", "Greedy"], "Wishing good",
          "Latin 'bene' (well) + 'volens' (wishing)."),
        q(500_016, "What is iambic pentameter?",
          ["A line with five iambs", "A line with four iambs", "A poem with no rhyme", "A two-line stanza"], "A line with five iambs",
          "Each iamb is unstressed/stressed (10 syllables)."),
        q(500_017, "What is a haiku?",
          ["Sonnet of 14 lines", "Three-line poem of 5/7/5 syllables", "Rhyming couplet", "Free verse poem"], "Three-line poem of 5/7/5 syllables",
          "Traditional Japanese form."),
        q(500_018, "What does 'antonym' mean?",
          ["Word with the same meaning", "Word with the opposite meaning", "Word with multiple meanings", "Word that imitates a sound"], "Word with the opposite meaning",
          "Greek 'anti' (against) + 'onyma' (name)."),
        q(500_019, "What does 'synonym' mean?",
          ["Word with the same meaning", "Word with the opposite meaning", "An imaginary word", "A word with no clear meaning"], "Word with the same meaning",
          "Greek 'syn' (with) + 'onyma' (name)."),
        q(500_020, "What is personification?",
          ["Comparison using 'like'", "Giving human traits to non-human things", "Repeated consonant sounds", "Deliberate exaggeration"], "Giving human traits to non-human things",
          "E.g. 'The wind whispered through the trees.'"),
        q(500_021, "What does 'meticulous' mean?",
          ["Quick and careless", "Showing great attention to detail", "Very loud", "Extremely shy"], "Showing great attention to detail",
          "Originally meant 'fearful' in Latin."),
        q(500_022, "What is a soliloquy?",
          ["A short poem", "A speech to oneself, usually on stage", "An imagined character", "A musical performance"], "A speech to oneself, usually on stage",
          "Famous example: Hamlet's 'To be, or not to be'."),
        q(500_023, "What is irony?",
          ["A type of metal", "A statement opposite to the literal meaning, often for effect", "A long poem", "A grammatical mistake"], "A statement opposite to the literal meaning, often for effect",
          "Three common types: verbal, situational, dramatic."),
        q(500_024, "What does 'pragmatic' mean?",
          ["Idealistic", "Practical and realistic", "Disorganised", "Theoretical"], "Practical and realistic",
          "From Greek 'pragma' — deed, action."),
        q(500_025, "What does 'ambivalent' mean?",
          ["Uninterested", "Having mixed feelings", "Loud and forceful", "Strongly opposed"], "Having mixed feelings",
          "Latin 'ambi-' (both) + 'valent' (strength)."),
        q(500_026, "What is an oxymoron?",
          ["A long sentence", "A figure of speech combining contradictory terms", "A type of paragraph", "A mistaken word choice"], "A figure of speech combining contradictory terms",
          "E.g. 'deafening silence', 'bittersweet'."),
        q(500_027, "What does 'lethargic' mean?",
          ["Energetic and lively", "Sluggish and lacking energy", "Frightened", "Curious"], "Sluggish and lacking energy",
          "From Greek 'lēthargos' — forgetful."),
        q(500_028, "What does the root 'aqua-' mean?",
          ["Earth", "Fire", "Air", "Water"], "Water",
          "Latin 'aqua' — water."),
        q(500_029, "What does the root 'bio-' mean?",
          ["Life", "Light", "Sound", "Time"], "Life",
          "Greek 'bios' — life."),
        q(500_030, "What does 'didactic' mean?",
          ["Intended to teach", "Difficult to understand", "Filled with humour", "Spoken in a whisper"], "Intended to teach",
          "From Greek 'didaktikos' — apt at teaching."),
        q(500_031, "What does 'eloquent' mean?",
          ["Boring and dull", "Fluent and persuasive in speech", "Overly emotional", "Brief and abrupt"], "Fluent and persuasive in speech",
          "Latin 'eloqui' — speak out."),
        q(500_032, "What is assonance?",
          ["Repetition of vowel sounds within nearby words", "Repetition of consonants at the start of words", "A pause in a line of poetry", "A type of rhyme scheme"], "Repetition of vowel sounds within nearby words",
          "E.g. 'the rain in Spain'.")
    ]

    static let flashcards: [Flashcard] = [
        Flashcard(front: "Ephemeral",      back: "Lasting a very short time."),
        Flashcard(front: "Ubiquitous",     back: "Present, appearing, or found everywhere."),
        Flashcard(front: "Onomatopoeia",   back: "A word that imitates the sound it represents (e.g. 'buzz')."),
        Flashcard(front: "Hyperbole",      back: "Deliberate exaggeration for emphasis."),
        Flashcard(front: "Iambic pentameter", back: "A line of verse with five iambs (10 syllables, alternating stress)."),
        Flashcard(front: "Soliloquy",      back: "A speech in a play in which a character speaks their thoughts aloud."),
        Flashcard(front: "Oxymoron",       back: "A figure of speech combining contradictory terms (e.g. 'bittersweet')."),
        Flashcard(front: "Alliteration",   back: "Repetition of the same initial consonant sound across nearby words."),
        Flashcard(front: "Personification", back: "Attribution of human characteristics to non-human things."),
        Flashcard(front: "Antonym",        back: "A word with the opposite meaning of another word."),
        Flashcard(front: "Synonym",        back: "A word with the same or nearly the same meaning as another."),
        Flashcard(front: "Metaphor",       back: "A figure of speech that directly equates one thing with another (no 'like'/'as')."),
        Flashcard(front: "Simile",         back: "A figure of speech comparing two things using 'like' or 'as'.")
    ]

    private static func q(_ id: Int, _ q: String, _ opts: [String], _ correct: String, _ why: String) -> QuizQuestion {
        QuizQuestion(id: id, type: .multipleChoice, question: q, options: opts, correctAnswer: correct, explanation: why)
    }
}
