//
//  CraterBlastBank.swift
//  WriteScholar
//
//  Direct port of src/data/craterBlastWordBank.ts — the full 426-question
//  general-knowledge "Play for Fun" pool used by Crater Blast on desktop.
//  No AI, no network, free for all users.
//
//  Each question always has 4 answers; correct index is 0 in the source
//  data and the iOS view shuffles the deck before display (matches
//  desktop behavior).
//

import Foundation

enum CraterBlastBank {

    /// Returns the full 426-question Play-for-Fun pool decoded into
    /// `CraterBlastQuestion` values ready for the native game view.
    static let playForFun: [CraterBlastQuestion] = Self.raw.map { Self.q(prompt: $0.0, answers: $0.1) }

    /// Convenience: shuffled pool for the Games tab demo so a session
    /// shows a different mix every time.
    static func shuffledPool(limit: Int? = nil) -> [CraterBlastQuestion] {
        let pool = playForFun.shuffled()
        if let n = limit { return Array(pool.prefix(n)) }
        return pool
    }

    // MARK: - Builder

    private static func q(prompt: String, answers: [String]) -> CraterBlastQuestion {
        let json: [String: Any] = [
            "id": UUID().uuidString,
            "prompt": prompt,
            "answers": answers,
            "correctIndex": 0
        ]
        let data = try! JSONSerialization.data(withJSONObject: json)
        return try! JSONDecoder().decode(CraterBlastQuestion.self, from: data)
    }

    // MARK: - Raw data (prompt, [correct, wrong1, wrong2, wrong3])
    //
    // Lines map 1:1 to the desktop word bank in order. Keeping them as
    // a flat tuple array keeps line count manageable and trivial to diff.

    private static let raw: [(String, [String])] = [
        ("What is the capital of France?", ["Paris","London","Berlin","Madrid"]),
        ("Which is the largest ocean on Earth?", ["Pacific","Atlantic","Indian","Arctic"]),
        ("What is the capital of Japan?", ["Tokyo","Osaka","Kyoto","Seoul"]),
        ("Which country has the largest land area?", ["Russia","Canada","China","USA"]),
        ("What is the longest river in the world?", ["Nile","Amazon","Mississippi","Yangtze"]),
        ("Which continent is the Sahara Desert in?", ["Africa","Asia","Australia","South America"]),
        ("What is the capital of Australia?", ["Canberra","Sydney","Melbourne","Perth"]),
        ("Which country is the Eiffel Tower in?", ["France","Italy","Spain","Germany"]),
        ("What is the smallest country in the world?", ["Vatican City","Monaco","San Marino","Liechtenstein"]),
        ("Which ocean is the Bermuda Triangle in?", ["Atlantic","Pacific","Indian","Caribbean"]),
        ("What is the capital of Canada?", ["Ottawa","Toronto","Vancouver","Montreal"]),
        ("Which country has the most islands?", ["Sweden","Indonesia","Philippines","Finland"]),
        ("What is the capital of Brazil?", ["Brasília","Rio de Janeiro","São Paulo","Buenos Aires"]),
        ("Which mountain is the tallest on Earth?", ["Mount Everest","K2","Kilimanjaro","Denali"]),
        ("What is the capital of Egypt?", ["Cairo","Alexandria","Luxor","Giza"]),
        ("What is the chemical symbol for gold?", ["Au","Ag","Fe","Cu"]),
        ("How many planets are in our solar system?", ["8","7","9","10"]),
        ("What is the chemical symbol for water?", ["H₂O","CO₂","NaCl","O₂"]),
        ("What is the speed of light (approx)?", ["300,000 km/s","150,000 km/s","500,000 km/s","100,000 km/s"]),
        ("What planet is known as the Red Planet?", ["Mars","Venus","Jupiter","Saturn"]),
        ("What is the largest organ in the human body?", ["Skin","Liver","Brain","Heart"]),
        ("How many bones are in the adult human body?", ["206","200","212","195"]),
        ("What gas do plants absorb from the air?", ["Carbon dioxide","Oxygen","Nitrogen","Hydrogen"]),
        ("What is the boiling point of water in Celsius?", ["100°C","90°C","110°C","212°C"]),
        ("Which planet has the most moons?", ["Saturn","Jupiter","Uranus","Neptune"]),
        ("What is the hardest natural substance?", ["Diamond","Graphite","Quartz","Topaz"]),
        ("What is the chemical symbol for iron?", ["Fe","Ir","Au","Ag"]),
        ("How many legs does a spider have?", ["8","6","10","12"]),
        ("What is the main gas in Earth's atmosphere?", ["Nitrogen","Oxygen","Carbon dioxide","Argon"]),
        ("What planet is closest to the Sun?", ["Mercury","Venus","Mars","Earth"]),
        ("In what year did World War II end?", ["1945","1944","1946","1943"]),
        ("Who was the first president of the United States?", ["George Washington","Thomas Jefferson","John Adams","Benjamin Franklin"]),
        ("In what year did the Titanic sink?", ["1912","1911","1913","1910"]),
        ("Who wrote the Declaration of Independence?", ["Thomas Jefferson","George Washington","Benjamin Franklin","John Adams"]),
        ("In what year did Columbus reach the Americas?", ["1492","1491","1500","1485"]),
        ("Who invented the light bulb?", ["Thomas Edison","Nikola Tesla","Benjamin Franklin","Alexander Graham Bell"]),
        ("What ancient wonder is still standing today?", ["Great Pyramid of Giza","Colossus of Rhodes","Hanging Gardens","Lighthouse of Alexandria"]),
        ("In what year did World War I begin?", ["1914","1915","1913","1916"]),
        ("Who was the first man on the Moon?", ["Neil Armstrong","Buzz Aldrin","Yuri Gagarin","John Glenn"]),
        ("What empire built the Colosseum?", ["Roman","Greek","Egyptian","Persian"]),
        ("In what year did the Berlin Wall fall?", ["1989","1988","1990","1991"]),
        ("Who painted the Mona Lisa?", ["Leonardo da Vinci","Michelangelo","Raphael","Vincent van Gogh"]),
        ("What country gave the Statue of Liberty to the USA?", ["France","England","Italy","Spain"]),
        ("In what year did humans first land on the Moon?", ["1969","1968","1970","1971"]),
        ("Who discovered gravity (apple story)?", ["Isaac Newton","Albert Einstein","Galileo","Copernicus"]),
        ("Who wrote Romeo and Juliet?", ["William Shakespeare","Charles Dickens","Jane Austen","Mark Twain"]),
        ("What is the first book of the Bible?", ["Genesis","Exodus","Matthew","Revelation"]),
        ("Who wrote Harry Potter?", ["J.K. Rowling","Stephen King","Roald Dahl","C.S. Lewis"]),
        ("What instrument has 88 keys?", ["Piano","Organ","Harpsichord","Synthesizer"]),
        ("Who painted The Starry Night?", ["Vincent van Gogh","Pablo Picasso","Claude Monet","Salvador Dalí"]),
        ("How many strings does a standard guitar have?", ["6","5","7","12"]),
        ("Who wrote 1984?", ["George Orwell","Aldous Huxley","Ray Bradbury","H.G. Wells"]),
        ("What is the smallest unit of sound in language?", ["Phoneme","Morpheme","Syllable","Letter"]),
        ("Who wrote Pride and Prejudice?", ["Jane Austen","Charlotte Brontë","Emily Brontë","Virginia Woolf"]),
        ("How many lines does a sonnet have?", ["14","12","16","10"]),
        ("Who wrote The Great Gatsby?", ["F. Scott Fitzgerald","Ernest Hemingway","John Steinbeck","William Faulkner"]),
        ("What art style did Picasso help create?", ["Cubism","Impressionism","Surrealism","Abstract"]),
        ("Who wrote To Kill a Mockingbird?", ["Harper Lee","John Steinbeck","Mark Twain","Toni Morrison"]),
        ("How many symphonies did Beethoven write?", ["9","5","7","12"]),
        ("Who wrote The Hobbit?", ["J.R.R. Tolkien","C.S. Lewis","George R.R. Martin","Terry Pratchett"]),
        ("How many players are on a soccer team?", ["11","10","12","9"]),
        ("What color is the center of a target?", ["Gold/Yellow","Red","Blue","White"]),
        ("How many points is a touchdown worth?", ["6","7","3","2"]),
        ("In what sport do you score a \"birdie\"?", ["Golf","Tennis","Badminton","Baseball"]),
        ("How many Grand Slam tournaments are there in tennis?", ["4","3","5","6"]),
        ("What country invented soccer?", ["England","Brazil","Italy","France"]),
        ("How many rings are on the Olympic flag?", ["5","4","6","7"]),
        ("In chess, what piece moves in an L shape?", ["Knight","Bishop","Rook","Queen"]),
        ("How many cards are in a standard deck?", ["52","48","54","50"]),
        ("What sport uses a shuttlecock?", ["Badminton","Tennis","Squash","Table tennis"]),
        ("How many players are on a basketball team?", ["5","6","4","7"]),
        ("What is Canada's national sport in summer?", ["Lacrosse","Hockey","Curling","Baseball"]),
        ("In bowling, what is a perfect game score?", ["300","200","400","250"]),
        ("How many bases are on a baseball diamond?", ["4","3","5","6"]),
        ("What country hosted the 2016 Summer Olympics?", ["Brazil","China","England","Japan"]),
        ("What fruit is associated with doctors?", ["Apple","Orange","Banana","Grape"]),
        ("What is the main ingredient in guacamole?", ["Avocado","Tomato","Lime","Onion"]),
        ("What country does sushi originate from?", ["Japan","China","Korea","Thailand"]),
        ("What vegetable is Popeye known for eating?", ["Spinach","Broccoli","Kale","Lettuce"]),
        ("What is the primary ingredient in hummus?", ["Chickpeas","Lentils","Beans","Peas"]),
        ("What nut is in pesto sauce?", ["Pine nut","Walnut","Almond","Cashew"]),
        ("What fruit do raisins come from?", ["Grapes","Dates","Prunes","Figs"]),
        ("What country is brie cheese from?", ["France","Italy","Switzerland","Netherlands"]),
        ("What is the main ingredient in tzatziki?", ["Yogurt","Sour cream","Cream cheese","Mayonnaise"]),
        ("What fruit has the most vitamin C?", ["Guava","Orange","Lemon","Strawberry"]),
        ("What grain is sake made from?", ["Rice","Wheat","Barley","Corn"]),
        ("What country does croissant originate from?", ["France","Austria","Belgium","Switzerland"]),
        ("What is the main ingredient in wasabi?", ["Horseradish","Mustard","Ginger","Garlic"]),
        ("What fruit is a key lime pie made from?", ["Lime","Lemon","Orange","Grapefruit"]),
        ("What country is paella from?", ["Spain","Italy","Portugal","France"]),
        ("What is the fastest land animal?", ["Cheetah","Lion","Gazelle","Horse"]),
        ("What is the largest mammal on Earth?", ["Blue whale","Elephant","Giraffe","Polar bear"]),
        ("What bird is the symbol of the United States?", ["Bald eagle","Turkey","Robin","Hawk"]),
        ("How many hearts does an octopus have?", ["3","1","2","4"]),
        ("What is the only mammal that can fly?", ["Bat","Flying squirrel","Sugar glider","Colugo"]),
        ("What animal has the longest neck?", ["Giraffe","Ostrich","Swan","Camel"]),
        ("What is a group of lions called?", ["Pride","Pack","Herd","Flock"]),
        ("What is the largest species of bear?", ["Polar bear","Grizzly","Brown bear","Black bear"]),
        ("What insect has the shortest lifespan?", ["Mayfly","Housefly","Mosquito","Ant"]),
        ("What is the only bird that can fly backward?", ["Hummingbird","Kingfisher","Woodpecker","Swift"]),
        ("What animal can regenerate its tail?", ["Lizard","Snake","Frog","Turtle"]),
        ("What is the largest land animal?", ["African elephant","Asian elephant","Rhino","Hippo"]),
        ("What is a baby kangaroo called?", ["Joey","Cub","Pup","Calf"]),
        ("What color is a polar bear's skin?", ["Black","White","Pink","Gray"]),
        ("What is 15% of 200?", ["30","25","35","20"]),
        ("How many sides does a hexagon have?", ["6","5","7","8"]),
        ("What is 7 × 8?", ["56","54","58","64"]),
        ("How many degrees in a right angle?", ["90","180","45","360"]),
        ("What is the square root of 144?", ["12","11","13","14"]),
        ("How many sides does an octagon have?", ["8","6","7","10"]),
        ("What is 12 × 12?", ["144","124","134","154"]),
        ("How many zeros are in one million?", ["6","5","7","9"]),
        ("What is 25% of 80?", ["20","25","15","30"]),
        ("How many sides does a pentagon have?", ["5","4","6","7"]),
        ("What is the value of pi (to 2 decimals)?", ["3.14","3.41","2.14","4.13"]),
        ("How many degrees in a triangle?", ["180","360","90","270"]),
        ("What is 9 × 9?", ["81","72","90","63"]),
        ("How many prime numbers are between 1 and 10?", ["4","3","5","6"]),
        ("What is 100 ÷ 4?", ["25","20","30","40"]),
        ("What company makes the iPhone?", ["Apple","Samsung","Google","Microsoft"]),
        ("What is the name of the wizard in Harry Potter?", ["Dumbledore","Gandalf","Merlin","Voldemort"]),
        ("What year was Facebook founded?", ["2004","2003","2005","2006"]),
        ("Who directed Jurassic Park?", ["Steven Spielberg","James Cameron","George Lucas","Ridley Scott"]),
        ("What is the highest-grossing film of all time?", ["Avatar","Avengers: Endgame","Titanic","Star Wars"]),
        ("What streaming service has Stranger Things?", ["Netflix","Disney+","HBO Max","Amazon Prime"]),
        ("Who played Iron Man in the MCU?", ["Robert Downey Jr.","Chris Evans","Chris Hemsworth","Mark Ruffalo"]),
        ("What is the capital of Westeros in Game of Thrones?", ["King's Landing","Winterfell","Dragonstone","The Eyrie"]),
        ("What year did YouTube launch?", ["2005","2004","2006","2007"]),
        ("Who sang \"Thriller\"?", ["Michael Jackson","Prince","Whitney Houston","Stevie Wonder"]),
        ("What is the name of the coffee shop in Friends?", ["Central Perk","Coffee House","The Brew","Café Nervosa"]),
        ("What band sang \"Bohemian Rhapsody\"?", ["Queen","The Beatles","Led Zeppelin","Pink Floyd"]),
        ("What is the longest-running Broadway show?", ["The Phantom of the Opera","Chicago","Cats","Les Misérables"]),
        ("What does CPU stand for?", ["Central Processing Unit","Computer Personal Unit","Central Program Utility","Core Processing Unit"]),
        ("What does HTML stand for?", ["HyperText Markup Language","High Tech Markup Language","Hyper Transfer Markup","Home Tool Markup Language"]),
        ("What year was the first iPhone released?", ["2007","2006","2008","2009"]),
        ("What does USB stand for?", ["Universal Serial Bus","United System Bus","Universal System Block","Unified Serial Block"]),
        ("Who founded Amazon?", ["Jeff Bezos","Elon Musk","Bill Gates","Mark Zuckerberg"]),
        ("What does RAM stand for?", ["Random Access Memory","Read Access Memory","Run Application Memory","Random Application Module"]),
        ("What company created the Android OS?", ["Google","Apple","Samsung","Microsoft"]),
        ("What does VPN stand for?", ["Virtual Private Network","Very Private Network","Virtual Public Network","Verified Private Network"]),
        ("Who founded Microsoft?", ["Bill Gates","Steve Jobs","Mark Zuckerberg","Larry Page"]),
        ("What does AI stand for?", ["Artificial Intelligence","Automated Intelligence","Advanced Integration","Algorithmic Interface"]),
        ("What year was Google founded?", ["1998","1997","1999","2000"]),
        ("What does PDF stand for?", ["Portable Document Format","Personal Data File","Print Document Format","Public Document File"]),
        ("What is the most used programming language?", ["JavaScript","Python","Java","C++"]),
        ("What is the fear of spiders called?", ["Arachnophobia","Claustrophobia","Acrophobia","Agoraphobia"]),
        ("How many days are in a leap year?", ["366","365","364","367"]),
        ("What is the opposite of evaporation?", ["Condensation","Precipitation","Sublimation","Transpiration"]),
        ("What color is an emerald?", ["Green","Blue","Red","Yellow"]),
        ("How many teeth does an adult human have?", ["32","28","30","36"]),
        ("What is the study of earthquakes called?", ["Seismology","Geology","Volcanology","Meteorology"]),
        ("What is the largest internal organ?", ["Liver","Heart","Brain","Lungs"]),
        ("How many continents are there?", ["7","6","5","8"]),
        ("What is the freezing point of water in Fahrenheit?", ["32°F","0°F","212°F","100°F"]),
        ("What is the smallest prime number?", ["2","1","0","3"]),
        ("How many hours are in a day?", ["24","12","48","36"]),
        ("What is the capital of Italy?", ["Rome","Milan","Venice","Florence"]),
        ("What is the study of birds called?", ["Ornithology","Zoology","Entomology","Ichthyology"]),
        ("How many weeks are in a year?", ["52","48","50","54"]),
        ("What is the chemical symbol for sodium?", ["Na","So","Sd","No"]),
        ("What is the largest desert in the world?", ["Antarctica","Sahara","Arabian","Gobi"]),
        ("What is the capital of Germany?", ["Berlin","Munich","Hamburg","Frankfurt"]),
        ("Which country has the most volcanoes?", ["Indonesia","Japan","USA","Philippines"]),
        ("What is the capital of Russia?", ["Moscow","St. Petersburg","Kiev","Warsaw"]),
        ("Which river flows through Paris?", ["Seine","Thames","Rhine","Danube"]),
        ("What is the capital of China?", ["Beijing","Shanghai","Hong Kong","Tokyo"]),
        ("Which country has the most time zones?", ["France","Russia","USA","UK"]),
        ("What is the capital of India?", ["New Delhi","Mumbai","Kolkata","Chennai"]),
        ("Which sea is the Dead Sea?", ["Salt lake","Ocean","River","Bay"]),
        ("What is the capital of South Korea?", ["Seoul","Busan","Incheon","Daegu"]),
        ("Which country is shaped like a boot?", ["Italy","Greece","Spain","Portugal"]),
        ("What is the capital of Spain?", ["Madrid","Barcelona","Seville","Valencia"]),
        ("Which ocean is the warmest?", ["Indian","Pacific","Atlantic","Arctic"]),
        ("What is the capital of Argentina?", ["Buenos Aires","Lima","Santiago","Montevideo"]),
        ("Which country has the most lakes?", ["Canada","Russia","Finland","USA"]),
        ("What is the capital of Mexico?", ["Mexico City","Guadalajara","Monterrey","Cancún"]),
        ("What is the chemical symbol for oxygen?", ["O","O₂","Ox","Og"]),
        ("What planet has the Great Red Spot?", ["Jupiter","Mars","Saturn","Neptune"]),
        ("What is the chemical symbol for carbon?", ["C","Ca","Co","Cr"]),
        ("What is the study of fungi called?", ["Mycology","Botany","Zoology","Microbiology"]),
        ("What is the chemical symbol for silver?", ["Ag","Au","Si","Sr"]),
        ("What is the closest star to Earth?", ["The Sun","Proxima Centauri","Alpha Centauri","Sirius"]),
        ("What is the chemical symbol for nitrogen?", ["N","Ni","Na","Ne"]),
        ("What is the study of insects called?", ["Entomology","Ornithology","Ichthyology","Herpetology"]),
        ("What is the chemical symbol for helium?", ["He","H","Hi","Ha"]),
        ("What is the largest moon in our solar system?", ["Ganymede","Titan","Callisto","Io"]),
        ("What is the chemical symbol for potassium?", ["K","P","Po","Pt"]),
        ("What is the study of the weather called?", ["Meteorology","Climatology","Geology","Astronomy"]),
        ("What is the chemical symbol for calcium?", ["Ca","C","Cl","Co"]),
        ("What is the speed of sound (approx)?", ["343 m/s","300 m/s","400 m/s","500 m/s"]),
        ("What is the chemical symbol for hydrogen?", ["H","He","Hy","Ha"]),
        ("Who invented the telephone?", ["Alexander Graham Bell","Thomas Edison","Nikola Tesla","Guglielmo Marconi"]),
        ("In what year did the US declare independence?", ["1776","1775","1777","1789"]),
        ("Who was the first woman to win a Nobel Prize?", ["Marie Curie","Mother Teresa","Malala","Jane Addams"]),
        ("In what year did the first computer get built?", ["1940s","1930s","1950s","1960s"]),
        ("Who developed the theory of relativity?", ["Albert Einstein","Isaac Newton","Stephen Hawking","Niels Bohr"]),
        ("In what year did the Cold War end?", ["1991","1989","1990","1992"]),
        ("Who was the first woman to fly solo across the Atlantic?", ["Amelia Earhart","Bessie Coleman","Harriet Quimby","Jacqueline Cochran"]),
        ("In what year did the internet become public?", ["1991","1989","1993","1995"]),
        ("Who invented the printing press?", ["Johannes Gutenberg","Benjamin Franklin","William Caxton","Aldus Manutius"]),
        ("In what year did the first airplane fly?", ["1903","1920","1895","1910"]),
        ("In what year did the Roman Empire fall?", ["476 AD","410 AD","500 AD","1453 AD"]),
        ("Who discovered penicillin?", ["Alexander Fleming","Louis Pasteur","Joseph Lister","Robert Koch"]),
        ("In what year did the first computer virus appear?", ["1986","1980","1990","1985"]),
        ("Who invented the radio?", ["Guglielmo Marconi","Nikola Tesla","Thomas Edison","Alexander Graham Bell"]),
        ("What is the capital of Greece?", ["Athens","Sparta","Thessaloniki","Crete"]),
        ("How many strings does a violin have?", ["4","3","5","6"]),
        ("What is the capital of Turkey?", ["Ankara","Istanbul","Izmir","Antalya"]),
        ("What is the largest organ in the human body by weight?", ["Skin","Liver","Brain","Heart"]),
        ("What is the capital of Poland?", ["Warsaw","Krakow","Gdansk","Poznan"]),
        ("How many bones are in the human spine?", ["33","26","24","30"]),
        ("What is the capital of Sweden?", ["Stockholm","Gothenburg","Malmo","Uppsala"]),
        ("What is the smallest bone in the human body?", ["Stapes","Incus","Malleus","Femur"]),
        ("What is the capital of Norway?", ["Oslo","Bergen","Stavanger","Trondheim"]),
        ("How many chambers does the human heart have?", ["4","2","3","5"]),
        ("What is the capital of Finland?", ["Helsinki","Turku","Tampere","Oulu"]),
        ("What is the rarest blood type?", ["AB negative","O negative","B negative","AB positive"]),
        ("What is the capital of Denmark?", ["Copenhagen","Aarhus","Odense","Aalborg"]),
        ("How many ribs does a human have?", ["24","20","22","26"]),
        ("What is the capital of Ireland?", ["Dublin","Cork","Galway","Limerick"]),
        ("What is a group of crows called?", ["Murder","Flock","Pack","Gaggle"]),
        ("How many dimples are on a standard golf ball?", ["336","300","400","256"]),
        ("What fruit takes the longest to grow?", ["Avocado","Pineapple","Mango","Banana"]),
        ("What is the only letter that doesn't appear in any US state name?", ["Q","Z","X","J"]),
        ("How many teeth does a snail have?", ["Around 14,000","100","50","0"]),
        ("What is the fear of long words called?", ["Hippopotomonstrosesquippedaliophobia","Logophobia","Verbophobia","Lexiphobia"]),
        ("What planet rains diamonds?", ["Uranus and Neptune","Saturn","Jupiter","Mars"]),
        ("How long is a moment (scientifically)?", ["90 seconds","60 seconds","30 seconds","2 minutes"]),
        ("What animal has fingerprints almost identical to humans?", ["Koala","Chimpanzee","Gorilla","Orangutan"]),
        ("What is the only mammal that can't jump?", ["Elephant","Hippo","Rhino","Sloth"]),
        ("How many times does a hummingbird's heart beat per minute?", ["Up to 1,260","500","300","200"]),
        ("What is the loudest animal on Earth?", ["Sperm whale","Blue whale","Lion","Howler monkey"]),
        ("What color is a polar bear's tongue?", ["Blue","Pink","Black","White"]),
        ("How many noses does a slug have?", ["4","1","2","0"]),
        ("What is the only food that never spoils?", ["Honey","Salt","Sugar","Rice"]),
        ("What percentage of our DNA do we share with bananas?", ["About 50%","10%","90%","25%"]),
        ("How many muscles does it take to frown?", ["43","20","10","50"]),
        ("What is the shortest war in history?", ["Anglo-Zanzibar War (38 min)","Six-Day War","Falklands War","Gulf War"]),
        ("What fruit is actually a berry?", ["Banana","Strawberry","Raspberry","Blackberry"]),
        ("How many eyes does a bee have?", ["5","2","4","6"]),
        ("What is the only metal that is liquid at room temperature?", ["Mercury","Gallium","Cesium","Bromine"]),
        ("What was the first video ever played on MTV?", ["Video Killed the Radio Star","Thriller","Like a Virgin","Billie Jean"]),
        ("What is the oldest soft drink in America?", ["Dr Pepper","Coca-Cola","Pepsi","Root beer"]),
        ("What planet spins backwards?", ["Venus","Uranus","Neptune","Pluto"]),
        ("How many taste buds does the average human have?", ["About 10,000","5,000","20,000","2,000"]),
        ("What is the only bird that can fly upside down?", ["Hummingbird","Swift","Eagle","Parrot"]),
        ("What is the most consumed manufactured drink in the world?", ["Tea","Coffee","Beer","Soda"]),
        ("How many bones does a shark have?", ["0","50","100","200"]),
        ("What is the longest word in English without a vowel?", ["Rhythms","Strengths","Twelfth","Syzygy"]),
        ("What animal can sleep for 3 years?", ["Snail","Bear","Bat","Frog"]),
        ("What is the only continent with no reptiles?", ["Antarctica","Greenland","Iceland","New Zealand"]),
        ("How many times can a piece of paper be folded in half?", ["About 7","10","12","5"]),
        ("What is the most stolen food in the world?", ["Cheese","Chocolate","Bacon","Shrimp"]),
        ("What planet has a hexagon-shaped storm?", ["Saturn","Jupiter","Neptune","Uranus"]),
        ("How many legs does a lobster have?", ["10","8","6","12"]),
        ("What is the only number spelled with letters in alphabetical order?", ["Forty","One","Two","Hundred"]),
        ("What animal has the strongest bite?", ["Nile crocodile","Great white shark","Hippo","Tiger"]),
        ("How many keys are on a standard piano?", ["88","76","92","100"]),
        ("What is the rarest M&M color?", ["Brown","Yellow","Red","Orange"]),
        ("What is the only rock that floats?", ["Pumice","Cork","Sponge","Lava rock"]),
        ("How many times does the average person blink per day?", ["About 15,000","5,000","25,000","10,000"]),
        ("What is the smallest country in Africa?", ["Seychelles","Gambia","Djibouti","Comoros"]),
        ("What fruit has its seeds on the outside?", ["Strawberry","Raspberry","Blackberry","Watermelon"]),
        ("How many stomachs does a cow have?", ["4","1","2","3"]),
        ("What is the only letter not on the periodic table?", ["J","Q","W","Z"]),
        ("What animal can hold its breath the longest?", ["Cuvier's beaked whale","Sperm whale","Elephant seal","Green sea turtle"]),
        ("How many faces does a dice have?", ["6","4","8","12"]),
        ("What is the most common blood type?", ["O positive","A positive","B positive","AB positive"]),
        ("What planet is closest in size to Earth?", ["Venus","Mars","Mercury","Neptune"]),
        ("How many teeth does a great white shark have?", ["About 300","50","100","500"]),
        ("What is the only fruit with seeds on the outside?", ["Strawberry","Pineapple","Kiwi","Fig"]),
        ("What is the fear of peanut butter sticking to the roof of your mouth?", ["Arachibutyrophobia","Arachnophobia","Glossophobia","Trypophobia"]),
        ("How many bones are in a giraffe's neck?", ["7","5","10","12"]),
        ("What is the most expensive spice by weight?", ["Saffron","Vanilla","Cardamom","Cinnamon"]),
        ("What animal has three hearts?", ["Octopus","Squid","Jellyfish","Starfish"]),
        ("How many planets could fit between Earth and the Moon?", ["All of them","5","10","None"]),
        ("What is the world's largest flower?", ["Rafflesia","Sunflower","Titan arum","Lotus"]),
        ("How many hearts does an earthworm have?", ["5","1","3","0"]),
        ("What is the only edible food that never expires?", ["Honey","Rice","Salt","Sugar"]),
        ("What animal has blue blood?", ["Horseshoe crab","Octopus","Squid","Lobster"]),
        ("How many muscles does it take to smile?", ["17","10","25","5"]),
        ("What is the fastest fish in the ocean?", ["Sailfish","Marlin","Tuna","Swordfish"]),
        ("What is the only fruit that grows on a tree and is also a nut?", ["Coconut","Almond","Walnut","Pecan"]),
        ("How many bones do babies have at birth?", ["About 300","206","150","250"]),
        ("What is the most venomous snake?", ["Inland taipan","Black mamba","King cobra","Rattlesnake"]),
        ("What is the only mammal that lays eggs?", ["Platypus and echidna","Seahorse","Shark","Frog"]),
        ("How many nostrils does a human have?", ["4","2","1","6"]),
        ("What is the heaviest organ in the human body?", ["Skin","Liver","Brain","Heart"]),
        ("What animal can see in ultraviolet?", ["Bees","Dogs","Cats","Humans"]),
        ("How many teeth does a blue whale have?", ["0","100","50","200"]),
        ("What is the only bird that can fly backward and hover?", ["Hummingbird","Kingfisher","Woodpecker","Swift"]),
        ("How many times does the average heart beat per day?", ["About 100,000","50,000","200,000","75,000"]),
        ("What is the most common nickname for a pet?", ["Max","Bella","Charlie","Lucy"]),
        ("What is the only bird that can swim but not fly?", ["Penguin","Ostrich","Emu","Kiwi"]),
        ("What is the loudest sound a human can make?", ["Scream (about 129 dB)","Whistle","Clap","Shout"]),
        ("How many teeth does an adult cat have?", ["30","28","32","26"]),
        ("What is the only metal that is a liquid at room temp?", ["Mercury","Gallium","Cesium","Francium"]),
        ("What animal sleeps with one eye open?", ["Dolphin","Shark","Frog","Owl"]),
        ("How many bones are in the human hand?", ["27","26","28","24"]),
        ("What is the only fruit named after a color?", ["Orange","Lemon","Lime","Apple"]),
        ("What is the fastest bird in the world?", ["Peregrine falcon","Eagle","Swift","Ostrich"]),
        ("How many muscles are in the human body?", ["Over 600","400","300","800"]),
        ("What is the only planet not named after a god?", ["Earth","Mars","Venus","Mercury"]),
        ("What animal has the best sense of smell?", ["Bloodhound","Bear","Shark","Elephant"]),
        ("How many bones are in the human ear?", ["3","2","4","5"]),
        ("How many eyes does a spider have?", ["Usually 8","6","4","2"]),
        ("What is the only bird that can fly backwards?", ["Hummingbird","Swift","Kingfisher","Woodpecker"]),
        ("How many bones does a human baby have?", ["About 300","206","250","350"]),
        ("What is the only continent without bees?", ["Antarctica","Greenland","Iceland","Australia"]),
        ("What is the most common element in the universe?", ["Hydrogen","Helium","Oxygen","Carbon"]),
        ("How many legs does a centipede have?", ["Between 30-354","100","50","Exactly 100"]),
        ("What is the longest bone in the human body?", ["Femur","Tibia","Humerus","Spine"]),
        ("How many stomachs does a goat have?", ["4","1","2","3"]),
        ("What is the only mammal that can truly fly?", ["Bat","Flying squirrel","Sugar glider","Colugo"]),
        ("What is the most abundant element in Earth's crust?", ["Oxygen","Silicon","Aluminum","Iron"]),
        ("How many teeth does a narwhal have?", ["2 (one is a tusk)","0","50","100"]),
        ("What is the only bird that can run faster than humans?", ["Ostrich","Emu","Rhea","Cassowary"]),
        ("What is the fear of the number 13?", ["Triskaidekaphobia","Numerophobia","Hexakosioihexekontahexaphobia","Arachnophobia"]),
        ("How many bones are in the human foot?", ["26","24","28","22"]),
        ("What is the most expensive coffee in the world?", ["Kopi Luwak","Blue Mountain","Hawaiian Kona","Ethiopian Yirgacheffe"]),
        ("How many teeth does a dog have?", ["42","32","38","44"]),
        ("What is the only planet that rotates on its side?", ["Uranus","Venus","Neptune","Pluto"]),
        ("What is the most venomous fish?", ["Stonefish","Lionfish","Pufferfish","Stingray"]),
        ("How many bones are in the human skull?", ["22","28","24","20"]),
        ("How many teeth does a crocodile have?", ["About 60","30","100","40"]),
        ("What is the most common eye color in the world?", ["Brown","Blue","Green","Hazel"]),
        ("How many bones does a human have?", ["206","200","212","195"]),
        ("What is the most consumed beverage worldwide (after water)?", ["Tea","Coffee","Beer","Soda"]),
        ("What is the fear of clowns called?", ["Coulrophobia","Arachnophobia","Acrophobia","Claustrophobia"]),
        ("What is the most common surname in the world?", ["Wang","Smith","Zhang","Li"]),
        ("What is the fear of Friday the 13th?", ["Paraskevidekatriaphobia","Triskaidekaphobia","Friggatriskaidekaphobia","Hexakosioihexekontahexaphobia"]),
        ("What is the most expensive spice?", ["Saffron","Vanilla","Cardamom","Cinnamon"]),
        ("What is the fear of mirrors?", ["Eisoptrophobia","Catoptrophobia","Spectrophobia","Reflectophobia"]),
        ("What is the most common name in the world?", ["Muhammad","Wei","John","Maria"]),
        ("What is the most consumed meat in the world?", ["Pork","Chicken","Beef","Fish"]),
        ("What is the most consumed fruit in America?", ["Banana","Apple","Orange","Strawberry"]),
        ("What is the most expensive fruit?", ["Japanese Yubari melon","Densuke watermelon","Ruby Roman grapes","Dragon fruit"]),
        ("What is the most expensive chocolate?", ["To'ak Chocolate","Amedei","Valrhona","Godiva"]),
        ("What is the most expensive cheese?", ["Pule","White Stilton Gold","Bitto Storico","Roquefort"]),
        ("What is the most expensive tea?", ["Da Hong Pao","Silver Needle","Tieguanyin","Matcha"]),
        ("What is the most expensive mushroom?", ["White truffle","Matsutake","Morel","Chanterelle"]),
        ("What is the most expensive honey?", ["Elvish honey","Manuka honey","Acacia honey","Buckwheat honey"]),
        ("What is the most expensive caviar?", ["Beluga","Osetra","Sevruga","Sterlet"]),
        ("What is the most expensive wine?", ["Romanée-Conti","Lafite","Petrus","Opus One"]),
        ("What is the most expensive whiskey?", ["Macallan Fine & Rare","Glenfiddich","Johnnie Walker","Jack Daniel's"]),
        ("What is the most expensive sushi?", ["Bluefin tuna","Salmon","Uni","Eel"]),
        ("What is the most expensive pizza?", ["Louis XIII","Margherita","Pepperoni","Hawaiian"]),
        ("What is the most expensive burger?", ["FleurBurger 5000","Big Mac","Whopper","In-N-Out"]),
        ("What is the most expensive ice cream?", ["Serendipity's Golden Opulence","Ben & Jerry's","Häagen-Dazs","Baskin-Robbins"]),
        ("What is the most expensive steak?", ["A5 Wagyu","Filet mignon","Ribeye","New York strip"]),
        ("What country invented ice cream?", ["China","Italy","France","Persia"]),
        ("How many dimples does a standard golf ball have?", ["336","256","392","412"]),
        ("What animal has fingerprints nearly identical to humans?", ["Koala","Chimpanzee","Gorilla","Orangutan"]),
        ("How long is a moment (in seconds)?", ["90","60","30","120"]),
        ("What fruit is a cross between a blackberry and a raspberry?", ["Boysenberry","Loganberry","Tayberry","Marionberry"]),
        ("What element has the chemical symbol Au?", ["Gold","Silver","Aluminum","Argon"]),
        ("How many times can a hummingbird flap its wings per second?", ["Up to 80","Up to 50","Up to 100","Up to 120"]),
        ("What is the speed of light in km/s?", ["About 300,000","About 150,000","About 450,000","About 200,000"]),
        ("What country has the most islands?", ["Sweden","Indonesia","Philippines","Finland"]),
        ("What is the only continent with no deserts?", ["Europe","Asia","Africa","Australia"]),
        ("What fruit floats in water?", ["Apples","Oranges","Bananas","All of them"]),
        ("What animal has the longest lifespan?", ["Greenland shark","Galápagos tortoise","Bowhead whale","Elephant"]),
        ("How many sides does a stop sign have?", ["8","6","10","4"]),
        ("What bird can fly the highest?", ["Rüppell's vulture","Eagle","Albatross","Condor"]),
        ("What is the tallest mammal?", ["Giraffe","Elephant","Moose","Camel"]),
        ("How many keys does a standard piano have?", ["88","76","96","72"]),
        ("How many stripes does a zebra have?", ["Unique to each zebra","26","50","100"]),
        ("What animal has the strongest bite force?", ["Nile crocodile","Great white shark","Hippo","Tiger"]),
        ("How many time zones does Russia have?", ["11","9","7","13"]),
        ("What is the only bird with nostrils at the tip of its beak?", ["Kiwi","Penguin","Ostrich","Emu"]),
        ("What is the most abundant element in the universe?", ["Hydrogen","Helium","Oxygen","Carbon"]),
        ("How many taste buds does a human have?", ["About 10,000","About 5,000","About 20,000","About 2,000"]),

        // ── 55 additional desktop-parity entries (ports the rest of CRATER_BLAST_WORD_BANK) ──
        // Entries with non-zero correctIndex on desktop have the correct
        // answer reordered to position 0 here; the game shuffles answers
        // for display anyway, so the visible randomness is preserved.
        ("In what sport do you score a \"birdie\"?", ["Golf","Tennis","Badminton","Baseball"]),
        ("What band sang \"Bohemian Rhapsody\"?", ["Queen","The Beatles","Led Zeppelin","Pink Floyd"]),
        ("Who sang \"Thriller\"?", ["Michael Jackson","Prince","Whitney Houston","Stevie Wonder"]),
        ("What does Wi-Fi stand for?", ["Nothing","Wireless Fidelity","Wide Fidelity","Wireless Internet"]),
        ("What is the name of the dragon in Game of Thrones?", ["All three","Drogon","Viserion","Rhaegal"]),
        ("Who created Mickey Mouse?", ["Both","Walt Disney","Ub Iwerks","Neither"]),
        ("Who founded Tesla?", ["Both","Elon Musk","Martin Eberhard","Neither"]),
        ("What mammal lays eggs?", ["Both","Platypus","Echidna","Neither"]),
        ("What is the only mammal that can't fart?", ["None - all mammals can","Sloth","Bat","Koala"]),
        ("What is the only mammal that can't swim?", ["All mammals can swim","Giraffe","Elephant","Hippo"]),
        ("Who wrote the Communist Manifesto?", ["Both Marx and Engels","Karl Marx","Vladimir Lenin","Friedrich Engels"]),
        ("What planet has the most moons?", ["Saturn","Jupiter","Uranus","Neptune"]),

        // "Fear of" series (Crater Blast trivia long-tail)
        ("What is the fear of beards?", ["Pogonophobia","Trichophobia","Chaetophobia","Barbophobia"]),
        ("What is the fear of calculators?", ["Calculophobia","Numerophobia","Machinephobia","Techphobia"]),
        ("What is the fear of chickens?", ["Alektorophobia","Ornithophobia","Aviophobia","Gallophobia"]),
        ("What is the fear of cooking?", ["Mageirocophobia","Cibophobia","Sitophobia","Bromophobia"]),
        ("What is the fear of even numbers?", ["Paranumerophobia","Numerophobia","Evenphobia","Pairphobia"]),
        ("What is the fear of fractions?", ["Numerophobia (math)","Fractionphobia","Decimalphobia","Divisionphobia"]),
        ("What is the fear of infinity?", ["Apeirophobia","Numerophobia","Infinitophobia","Endlessnessphobia"]),
        ("What is the fear of mathematical equations?", ["Numerophobia","Equationphobia","Mathphobia","Algebraphobia"]),
        ("What is the fear of money?", ["Chrematophobia","Peniaphobia","Plutophobia","Argentophobia"]),
        ("What is the fear of negative numbers?", ["Negativenumerophobia","Numerophobia","Minusphobia","Belowzerophobia"]),
        ("What is the fear of odd numbers?", ["Imparnumerophobia","Numerophobia","Oddphobia","Unevenphobia"]),
        ("What is the fear of prime numbers?", ["Primonumerophobia","Numerophobia","Primephobia","Firstphobia"]),
        ("What is the fear of Roman numerals?", ["Romanumerophobia","Numerophobia","Latinphobia","Classicalphobia"]),
        ("What is the fear of sleep?", ["Somniphobia","Hypnophobia","Oneirophobia","Nyctophobia"]),
        ("What is the fear of the color yellow?", ["Xanthophobia","Chromophobia","Luteophobia","Flavophobia"]),
        ("What is the fear of the number 0?", ["Oudenophobia","Numerophobia","Zerophobia","Nullophobia"]),
        ("What is the fear of the number 1?", ["Henophobia","Numerophobia","Monophobia","Unophobia"]),
        ("What is the fear of the number 2?", ["Dyophobia","Numerophobia","Duophobia","Biphobia"]),
        ("What is the fear of the number 4?", ["Tetraphobia","Numerophobia","Quatrophobia","Quadrophobia"]),
        ("What is the fear of the number 5?", ["Pentaphobia","Numerophobia","Quinophobia","Pempophobia"]),
        ("What is the fear of the number 6?", ["Hexaphobia","Numerophobia","Sexaphobia","Sixophobia"]),
        ("What is the fear of the number 7?", ["Heptaphobia","Numerophobia","Septophobia","Luckyphobia"]),
        ("What is the fear of the number 8?", ["Octophobia","Numerophobia","Arithmophobia","Octophobia (fear of figure 8)"]),
        ("What is the fear of the number 9?", ["Enneaphobia","Numerophobia","Novemphobia","Nonaphobia"]),
        ("What is the fear of the number 10?", ["Decaphobia","Numerophobia","Tenophobia","Dekaphobia"]),
        ("What is the fear of the number 100?", ["Hecatonophobia","Numerophobia","Centophobia","Hundredphobia"]),
        ("What is the fear of the number 666?", ["Hexakosioihexekontahexaphobia","Triskaidekaphobia","Numerophobia","Satanophobia"]),
        ("What is the fear of the number 1000?", ["Chiliaphobia","Numerophobia","Milliphobia","Thousandphobia"]),
        ("What is the fear of vegetables?", ["Lachanophobia","Botanophobia","Phytophobia","Vegetophobia"]),

        // "Most expensive X" series
        ("What is the most expensive crab?", ["Spider crab","King crab","Snow crab","Dungeness"]),
        ("What is the most expensive cupcake?", ["The Golden Phoenix","Sprinkles","Magnolia","Crumbs"]),
        ("What is the most expensive donut?", ["The Golden Cristal","Krispy Kreme","Dunkin'","Voodoo"]),
        ("What is the most expensive hot dog?", ["Tokyo Dog","Nathan's","Hebrew National","Oscar Mayer"]),
        ("What is the most expensive lobster?", ["Blue lobster","Maine lobster","Spiny lobster","Rock lobster"]),
        ("What is the most expensive nut?", ["Macadamia","Pine nut","Pistachio","Walnut"]),
        ("What is the most expensive oyster?", ["Coffin Bay","Kumamoto","Pacific","Belon"]),
        ("What is the most expensive popcorn?", ["Berco's Popcorn","Orville Redenbacher's","Smartfood","SkinnyPop"]),
        ("What is the most expensive potato chip?", ["St. Erik's","Pringles","Lay's","Kettle"]),
        ("What is the most expensive salad?", ["Frutti di Mare","Caesar","Greek","Cobb"]),
        ("What is the most expensive sandwich?", ["Von Essen Platinum Club","PB&J","Club sandwich","Reuben"]),
        ("What is the most expensive scallop?", ["Hokkaido scallop","Bay scallop","Sea scallop","Calico scallop"]),
        ("What is the most expensive shrimp?", ["Spot prawn","Tiger shrimp","Pink shrimp","Rock shrimp"]),
        ("What is the most expensive soup?", ["Buddha Jumps Over the Wall","French onion","Tomato","Chicken noodle"]),
        ("What is the most expensive taco?", ["The $25,000 taco","Taco Bell","Chipotle","Del Taco"])
    ]
}
